name:                mbnf-parser
version:             0.1.0.0
github:              "julianpeeters/mbnf-parser"
license:             BSD3
author:              "Julian Peeters"
maintainer:          "julianpeeters@gmail.com"
copyright:           "2022 Julian Peeters"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/julianpeeters/mbnf-parser#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- resourcet

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  mbnf-parser-exe:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mbnf-parser

tests:
  mbnf-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mbnf-parser
